"""FastAPI REST adapter for ShelterPulse."""
from __future__ import annotations

import asyncio
import dataclasses
import io
import json
import os
import pickle
import tempfile
import zipfile
from pathlib import Path
from uuid import uuid4

import fastapi
import numpy as np
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, model_validator

from shelterpulse.core.montecarlo import make_seed_set
from shelterpulse.core.schema import Scenario, load_scenario
from shelterpulse.optimize.baselines import ALL_BASELINES
from shelterpulse.optimize.interface import evaluate_candidate
from shelterpulse.optimize.workflow import CandidateAllocation, run_optimization_sweep
from shelterpulse.queue import get_publisher
from shelterpulse.queue.job_store import JobStatus, job_store
from shelterpulse.api.rate_limit import (
    check_rate_limit,
    export_limiter,
    get_client_ip,
    optimize_limiter,
    simulate_limiter,
)

_ALLOWED_ORIGINS = [
    "https://sh-f52a79071fe149e0ac99448fc11e8496.ecs.us-east-1.on.aws",
    "http://localhost:3000",
    "http://localhost:8000",
]

app = fastapi.FastAPI(title="ShelterPulse API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=_ALLOWED_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["Content-Type"],
)

_SCENARIO_PATH = Path(__file__).parent.parent.parent / "scenarios" / "whisker_haven.yaml"
_CACHE_PATH = Path(__file__).parent.parent.parent / "scenarios" / "whisker_haven_cache.pkl"
_scenario: Scenario | None = None


def _get_scenario() -> Scenario:
    global _scenario
    if _scenario is None:
        _scenario = load_scenario(_SCENARIO_PATH)
    return _scenario


def _load_demo_cache() -> list | None:
    if _CACHE_PATH.exists():
        with open(_CACHE_PATH, "rb") as f:
            return pickle.load(f)  # nosec B301 — local file generated by precompute_demo.py, not user input
    return None


# ── Request / Response models ─────────────────────────────────────────────────

class AllocationIn(BaseModel):
    foster_support: float = 0.25
    clinic_hours: float = 0.25
    temporary_isolation: float = 0.25
    adoption_events: float = 0.25

    @model_validator(mode="after")
    def shares_bounded(self) -> "AllocationIn":
        total = self.foster_support + self.clinic_hours + self.temporary_isolation + self.adoption_events
        if total > 1.0 + 1e-6:
            raise ValueError(f"shares sum to {total:.3f}, must be <= 1.0")
        return self


class SimulateRequest(BaseModel):
    allocation: AllocationIn = AllocationIn()
    n_replications: int = 64

    @model_validator(mode="after")
    def clamp_replications(self) -> "SimulateRequest":
        if self.n_replications < 1:
            raise ValueError("n_replications must be >= 1")
        if self.n_replications > 128:
            raise ValueError("n_replications must be <= 128")
        return self


class SweepRequest(BaseModel):
    n_candidates: int = 30
    n_replications: int = 64
    use_bo: bool = True

    @model_validator(mode="after")
    def clamp_params(self) -> "SweepRequest":
        if self.n_candidates < 1 or self.n_candidates > 50:
            raise ValueError("n_candidates must be between 1 and 50")
        if self.n_replications < 1 or self.n_replications > 128:
            raise ValueError("n_replications must be between 1 and 128")
        return self


class EvaluationOut(BaseModel):
    foster_support: float
    clinic_hours: float
    temporary_isolation: float
    adoption_events: float
    mean_overflow_cat_days: float
    std_overflow_cat_days: float
    mean_total_cost: float
    is_feasible: bool
    ci95_overflow_low: float = 0.0
    ci95_overflow_high: float = 0.0
    ci95_cost_low: float = 0.0
    ci95_cost_high: float = 0.0


class BuilderRequest(BaseModel):
    """Simplified 9-field form from the UI custom builder."""
    duration_days: int = 90
    housing_capacity: int = 35
    isolation_slots: int = 5
    vet_tech_fte: float = 1.5
    intervention_budget: float = 5000.0
    mean_intake_per_day: float = 3.8
    kitten_fraction: float = 0.59
    base_adoption_rate: float = 0.08
    n_replications: int = 32
    allocation: AllocationIn | None = None

    @model_validator(mode="after")
    def clamp_params(self) -> "BuilderRequest":
        if self.duration_days < 1 or self.duration_days > 365:
            raise ValueError("duration_days must be between 1 and 365")
        if self.housing_capacity < 1 or self.housing_capacity > 500:
            raise ValueError("housing_capacity must be between 1 and 500")
        if self.isolation_slots < 0 or self.isolation_slots > 100:
            raise ValueError("isolation_slots must be between 0 and 100")
        if self.vet_tech_fte < 0.1 or self.vet_tech_fte > 20.0:
            raise ValueError("vet_tech_fte must be between 0.1 and 20.0")
        if self.intervention_budget < 0 or self.intervention_budget > 1_000_000:
            raise ValueError("intervention_budget must be between 0 and 1,000,000")
        if self.mean_intake_per_day < 0.1 or self.mean_intake_per_day > 50.0:
            raise ValueError("mean_intake_per_day must be between 0.1 and 50.0")
        if self.kitten_fraction < 0.0 or self.kitten_fraction > 1.0:
            raise ValueError("kitten_fraction must be between 0.0 and 1.0")
        if self.base_adoption_rate < 0.0 or self.base_adoption_rate > 1.0:
            raise ValueError("base_adoption_rate must be between 0.0 and 1.0")
        if self.n_replications < 1 or self.n_replications > 128:
            raise ValueError("n_replications must be between 1 and 128")
        return self


class SensitivityPoint(BaseModel):
    param: str
    direction: str   # "high" or "low"
    delta: float     # ±20%
    mean_overflow_cat_days: float


class TimelinePoint(BaseModel):
    day: int
    housing_used: int
    overflow: int


# ── Helpers ───────────────────────────────────────────────────────────────────

def _er_to_out(r) -> EvaluationOut:
    return EvaluationOut(
        **dataclasses.asdict(r.allocation),
        mean_overflow_cat_days=r.mean_overflow_cat_days,
        std_overflow_cat_days=r.std_overflow_cat_days,
        mean_total_cost=r.mean_total_cost,
        is_feasible=r.is_feasible,
        ci95_overflow_low=r.ci95_overflow_low,
        ci95_overflow_high=r.ci95_overflow_high,
        ci95_cost_low=r.ci95_cost_low,
        ci95_cost_high=r.ci95_cost_high,
    )


def _builder_to_scenario(req: BuilderRequest) -> Scenario:
    """Build a minimal Scenario from builder form fields."""
    import yaml
    base_raw = yaml.safe_load(_SCENARIO_PATH.read_text(encoding="utf-8"))

    # Patch the relevant fields
    base_raw["duration_days"] = req.duration_days
    base_raw["housing_capacity"] = req.housing_capacity
    base_raw["isolation_capacity"] = req.isolation_slots
    base_raw["total_intervention_budget"] = req.intervention_budget
    base_raw["intake_rate_per_day"] = req.mean_intake_per_day

    # Adjust foster network to a sane fraction of housing
    base_raw["foster_network"]["capacity"] = max(1, req.housing_capacity // 4)

    # Scale workforce vet_tech fte
    for w in base_raw["workforce"]:
        if w["role"] == "vet_tech":
            w["fte"] = req.vet_tech_fte

    # Rebuild intake profiles from kitten_fraction
    kf = max(0.01, min(0.99, req.kitten_fraction))
    af = 1.0 - kf
    base_raw["intake_profiles"] = [
        {"age_class": "weaned_kitten", "health_status": "healthy", "weight": round(kf * 0.6, 4)},
        {"age_class": "neonatal", "health_status": "medical_hold", "weight": round(kf * 0.4, 4)},
        {"age_class": "adult", "health_status": "healthy", "weight": round(af * 0.7, 4)},
        {"age_class": "adult", "health_status": "isolation_required", "weight": round(af * 0.3, 4)},
    ]
    # Normalise weights to sum exactly to 1.0
    weights: list[float] = [float(p["weight"]) for p in base_raw["intake_profiles"]]
    total = sum(weights)
    for p in base_raw["intake_profiles"]:
        p["weight"] = round(float(p["weight"]) / total, 6)

    return Scenario.model_validate(base_raw)


# ── Core endpoints ────────────────────────────────────────────────────────────

@app.get("/health")
def health() -> dict:
    return {"status": "ok", "scenario": _get_scenario().name}


@app.post("/simulate", response_model=EvaluationOut)
def simulate(req: SimulateRequest, request: fastapi.Request) -> EvaluationOut:
    check_rate_limit(simulate_limiter, request)
    scenario = _get_scenario()
    alloc = CandidateAllocation(**req.allocation.model_dump())
    seeds = make_seed_set(scenario.seed, req.n_replications)
    return _er_to_out(evaluate_candidate(alloc, scenario, seeds))


@app.post("/optimize", response_model=list[EvaluationOut])
def optimize(req: SweepRequest, request: fastapi.Request) -> list[EvaluationOut]:
    check_rate_limit(optimize_limiter, request)
    # Cache hit for demo params (must match scripts/precompute_demo.py: 10 candidates, 16 reps, BO)
    if req.n_candidates == 10 and req.n_replications == 16 and req.use_bo:
        cached = _load_demo_cache()
        if cached:
            return [_er_to_out(r) for r in cached]

    scenario = _get_scenario()
    seeds = make_seed_set(scenario.seed, req.n_replications)
    results = run_optimization_sweep(
        scenario, budget=scenario.total_intervention_budget,
        n_candidates=req.n_candidates, seed_set=seeds, use_bo=req.use_bo,
    )
    return [_er_to_out(r) for r in results]


@app.get("/baselines", response_model=dict[str, AllocationIn])
def baselines() -> dict:
    return {name: AllocationIn(**dataclasses.asdict(alloc)) for name, alloc in ALL_BASELINES.items()}


# ── Builder endpoints ─────────────────────────────────────────────────────────

@app.post("/simulate/builder", response_model=EvaluationOut)
def simulate_builder(req: BuilderRequest, request: fastapi.Request) -> EvaluationOut:
    check_rate_limit(simulate_limiter, request)
    scenario = _builder_to_scenario(req)
    alloc = CandidateAllocation(0.25, 0.25, 0.25, 0.25)
    seeds = make_seed_set(scenario.seed, req.n_replications)
    return _er_to_out(evaluate_candidate(alloc, scenario, seeds))


@app.post("/optimize/builder")
async def optimize_builder(req: BuilderRequest, request: fastapi.Request, response: fastapi.Response):
    """Run BO optimization on a custom builder scenario.

    When QUEUE_BACKEND=sync (default): blocks and returns list[EvaluationOut] (200).
    When QUEUE_BACKEND=rabbitmq|sqs: dispatches async, returns job_id (202).
    """
    check_rate_limit(optimize_limiter, request)
    queue_backend = os.getenv("QUEUE_BACKEND", "sync")

    if queue_backend == "sync":
        # Existing synchronous behavior
        scenario = _builder_to_scenario(req)
        seeds = make_seed_set(scenario.seed, req.n_replications)
        results = run_optimization_sweep(
            scenario, budget=req.intervention_budget,
            n_candidates=15, seed_set=seeds, use_bo=True,
        )
        return [_er_to_out(r) for r in results]

    # Async dispatch: publish to queue and return immediately
    ip = get_client_ip(request)
    _MAX_CONCURRENT_JOBS = 3
    if job_store.count_active_by_ip(ip) >= _MAX_CONCURRENT_JOBS:
        raise fastapi.HTTPException(
            status_code=429,
            detail=f"Too many active jobs ({_MAX_CONCURRENT_JOBS} max). Wait for current jobs to complete.",
        )

    job_id = str(uuid4())
    job_store.create(job_id, total=20, client_ip=ip)  # 15 BO candidates + 5 baselines
    publisher = get_publisher()
    await publisher.publish_job(job_id, {
        "type": "optimize_builder",
        "request": req.model_dump(),
    })
    response.status_code = 202
    return {"job_id": job_id, "status": "queued"}


# ── Job status endpoints ──────────────────────────────────────────────────────

@app.get("/optimize/{job_id}/status")
def get_job_status(job_id: str):
    """Poll the status of an async optimization job."""
    job = job_store.get(job_id)
    if not job:
        raise fastapi.HTTPException(status_code=404, detail="Job not found")
    return {
        "job_id": job.job_id,
        "status": job.status.value,
        "progress_done": job.progress_done,
        "progress_total": job.progress_total,
    }


@app.get("/optimize/{job_id}/results")
def get_job_results(job_id: str):
    """Retrieve results of a completed optimization job."""
    job = job_store.get(job_id)
    if not job:
        raise fastapi.HTTPException(status_code=404, detail="Job not found")
    if job.status == JobStatus.FAILED:
        raise fastapi.HTTPException(status_code=500, detail=job.error or "Job failed")
    if job.status != JobStatus.COMPLETED:
        raise fastapi.HTTPException(status_code=409, detail=f"Job is {job.status.value}, not completed")
    return job.results


# ── SSE progress streaming ────────────────────────────────────────────────────

_SSE_TIMEOUT_SECONDS = 300  # 5 minutes


@app.get("/optimize/{job_id}/stream")
async def stream_job_progress(job_id: str):
    """Server-Sent Events stream for real-time job progress.

    Emits events:
      - event: progress, data: {"done": X, "total": N}
      - event: complete, data: {"results": [...]}
      - event: error, data: {"message": "..."}

    Stream closes on completion, error, or 5-min timeout.
    """
    job = job_store.get(job_id)
    if not job:
        raise fastapi.HTTPException(status_code=404, detail="Job not found")

    async def event_generator():
        queue = job_store.subscribe(job_id)
        try:
            # Emit current state immediately (in case progress already advanced)
            current_job = job_store.get(job_id)
            if current_job:
                if current_job.status == JobStatus.COMPLETED:
                    yield f"event: complete\ndata: {json.dumps({'results': current_job.results})}\n\n"
                    return
                if current_job.status == JobStatus.FAILED:
                    yield f"event: error\ndata: {json.dumps({'message': current_job.error or 'Job failed'})}\n\n"
                    return
                if current_job.progress_done > 0:
                    yield f"event: progress\ndata: {json.dumps({'done': current_job.progress_done, 'total': current_job.progress_total})}\n\n"

            # Stream events as they arrive
            while True:
                try:
                    event = await asyncio.wait_for(queue.get(), timeout=_SSE_TIMEOUT_SECONDS)
                except asyncio.TimeoutError:
                    yield f"event: error\ndata: {json.dumps({'message': 'Stream timeout'})}\n\n"
                    return

                event_type = event.get("event", "progress")
                if event_type == "progress":
                    yield f"event: progress\ndata: {json.dumps({'done': event['done'], 'total': event['total']})}\n\n"
                elif event_type == "complete":
                    yield f"event: complete\ndata: {json.dumps({'results': event['results']})}\n\n"
                    return
                elif event_type == "error":
                    yield f"event: error\ndata: {json.dumps({'message': event['message']})}\n\n"
                    return
        finally:
            job_store.unsubscribe(job_id, queue)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )


# ── Internal webhook endpoints (called by workers) ────────────────────────────

_INTERNAL_KEY = os.getenv("INTERNAL_KEY", "dev-key-123")


@app.post("/internal/jobs/{job_id}/progress")
def receive_job_progress(job_id: str, request: fastapi.Request, payload: dict):
    """Worker reports progress for a running job."""
    _validate_internal_key(request)
    job_store.update_progress(job_id, payload.get("done", 0), payload.get("total", 0))
    return {"ok": True}


@app.post("/internal/jobs/{job_id}/complete")
def receive_job_complete(job_id: str, request: fastapi.Request, payload: dict):
    """Worker reports job completion with results."""
    _validate_internal_key(request)
    job_store.complete(job_id, payload.get("results", []))
    return {"ok": True}


@app.post("/internal/jobs/{job_id}/fail")
def receive_job_fail(job_id: str, request: fastapi.Request, payload: dict):
    """Worker reports job failure."""
    _validate_internal_key(request)
    job_store.fail(job_id, payload.get("error", "Unknown error"))
    return {"ok": True}


def _validate_internal_key(request: fastapi.Request) -> None:
    """Check X-Internal-Key header matches expected value."""
    key = request.headers.get("X-Internal-Key", "")
    if key != _INTERNAL_KEY:
        raise fastapi.HTTPException(status_code=403, detail="Invalid internal key")


class CompareOut(BaseModel):
    winner: EvaluationOut
    baselines: dict[str, EvaluationOut]


@app.post("/optimize/builder/compare", response_model=CompareOut)
def optimize_builder_compare(req: BuilderRequest, request: fastapi.Request) -> CompareOut:
    """Run BO optimization + evaluate all baselines against a custom scenario."""
    check_rate_limit(optimize_limiter, request)
    scenario = _builder_to_scenario(req)
    seeds = make_seed_set(scenario.seed, req.n_replications)
    results = run_optimization_sweep(
        scenario, budget=req.intervention_budget,
        n_candidates=15, seed_set=seeds, use_bo=True,
    )
    winner = results[0]
    baseline_results = {
        name: _er_to_out(evaluate_candidate(alloc, scenario, list(seeds)))
        for name, alloc in ALL_BASELINES.items()
    }
    return CompareOut(winner=_er_to_out(winner), baselines=baseline_results)


# ── Sensitivity endpoint ──────────────────────────────────────────────────────

def _sensitivity_points(alloc: CandidateAllocation, seeds: list[int], raw: dict) -> list[SensitivityPoint]:
    """Vary intake_rate, housing_capacity, isolation_capacity ±20%; return 6 SensitivityPoints."""
    import yaml
    from shelterpulse.core.schema import Scenario as Sc
    params = {
        "intake_rate_per_day": raw["intake_rate_per_day"],
        "housing_capacity": raw["housing_capacity"],
        "isolation_capacity": raw["isolation_capacity"],
    }
    points: list[SensitivityPoint] = []
    for param, base_val in params.items():
        for direction, delta in [("high", 1.2), ("low", 0.8)]:
            patched = dict(raw)
            patched[param] = max(1, int(base_val * delta)) if isinstance(base_val, int) else base_val * delta
            overflow = evaluate_candidate(alloc, Sc.model_validate(patched), seeds).mean_overflow_cat_days
            points.append(SensitivityPoint(param=param, direction=direction, delta=delta, mean_overflow_cat_days=overflow))
    return points


@app.post("/sensitivity", response_model=list[SensitivityPoint])
def sensitivity(req: SimulateRequest) -> list[SensitivityPoint]:
    """Tornado chart data for Whisker Haven demo scenario."""
    import yaml
    alloc = CandidateAllocation(**req.allocation.model_dump())
    seeds = make_seed_set(_get_scenario().seed, req.n_replications)
    raw = yaml.safe_load(_SCENARIO_PATH.read_text(encoding="utf-8"))
    return _sensitivity_points(alloc, seeds, raw)


@app.post("/sensitivity/builder", response_model=list[SensitivityPoint])
def sensitivity_builder(req: BuilderRequest) -> list[SensitivityPoint]:
    """Tornado chart data for a custom builder scenario."""
    import yaml
    scenario = _builder_to_scenario(req)
    alloc = CandidateAllocation(0.25, 0.25, 0.25, 0.25)
    seeds = make_seed_set(scenario.seed, req.n_replications)
    # Build raw dict from builder params for patching
    raw = yaml.safe_load(_SCENARIO_PATH.read_text(encoding="utf-8"))
    raw["intake_rate_per_day"] = req.mean_intake_per_day
    raw["housing_capacity"] = req.housing_capacity
    raw["isolation_capacity"] = req.isolation_slots
    return _sensitivity_points(alloc, seeds, raw)


# ── Timeline endpoints ────────────────────────────────────────────────────────

def _run_timeline(scenario, alloc: CandidateAllocation) -> list[TimelinePoint]:
    """Daily housing occupancy + overflow for one simulation run (seed=scenario.seed).

    overflow = cats queued for housing (above capacity). simpy.Resource.count is
    capped at capacity, so the housing queue length is the real "above capacity" signal.
    """
    import simpy

    from shelterpulse.core.engine import _Counters, _intake_generator
    from shelterpulse.core.interventions import resolve_intervention

    intervention = resolve_intervention(
        alloc.foster_support, alloc.clinic_hours,
        alloc.temporary_isolation, alloc.adoption_events, scenario,
    )

    rng = np.random.default_rng(scenario.seed)
    env = simpy.Environment()
    isolation_cap = scenario.isolation_capacity
    extra_isolation = intervention.extra_isolation_slots
    extra_foster = intervention.extra_foster_slots
    vet_cap = max(1, int(sum(w.fte for w in scenario.workforce if w.role.value == "vet_tech")))
    if intervention.extra_vet_tech_fte > 0:
        vet_cap += max(1, round(intervention.extra_vet_tech_fte))

    resources = {
        "vet_tech": simpy.Resource(env, capacity=vet_cap),
        "animal_care": simpy.Resource(env, capacity=max(1, int(
            sum(w.fte for w in scenario.workforce if w.role.value == "animal_care")))),
        "foster_coordinator": simpy.Resource(env, capacity=max(1, int(
            sum(w.fte for w in scenario.workforce if w.role.value == "foster_coordinator")))),
        "housing": simpy.Resource(env, capacity=scenario.housing_capacity),
        "isolation": simpy.Resource(env, capacity=isolation_cap + extra_isolation),
        "foster": simpy.Resource(env, capacity=scenario.foster_network.capacity + extra_foster),
    }

    counters = _Counters()
    daily_snapshots: list[dict] = []

    def _daily_sampler():
        for day in range(scenario.duration_days):
            yield env.timeout(24.0)
            daily_snapshots.append({
                "day": day + 1,
                "housing_used": resources["housing"].count,
                "overflow": len(resources["housing"].queue),
            })

    env.process(_intake_generator(env, scenario, resources, counters, rng,
                                  intervention.adoption_wait_multiplier))
    env.process(_daily_sampler())
    # +1h past the last 24h boundary: SimPy does not run events scheduled exactly at
    # `until`, so without this the final daily sample (at day*24) is dropped — a 1-day
    # scenario would return an empty timeline and an N-day one only N-1 points.
    env.run(until=scenario.duration_days * 24.0 + 1.0)

    return [TimelinePoint(**s) for s in daily_snapshots]


@app.post("/simulate/timeline", response_model=list[TimelinePoint])
def simulate_timeline(req: SimulateRequest) -> list[TimelinePoint]:
    """Daily housing_used + overflow for the Whisker Haven demo scenario."""
    alloc = CandidateAllocation(**req.allocation.model_dump())
    return _run_timeline(_get_scenario(), alloc)


@app.post("/simulate/timeline/builder", response_model=list[TimelinePoint])
def simulate_timeline_builder(req: BuilderRequest) -> list[TimelinePoint]:
    """Daily housing_used + overflow for a custom builder scenario."""
    alloc = CandidateAllocation(**req.allocation.model_dump()) if req.allocation else CandidateAllocation(0.25, 0.25, 0.25, 0.25)
    return _run_timeline(_builder_to_scenario(req), alloc)


class TimelineCompareOut(BaseModel):
    before: list[TimelinePoint]
    after: list[TimelinePoint]


@app.post("/simulate/timeline/builder/compare", response_model=TimelineCompareOut)
def simulate_timeline_builder_compare(req: BuilderRequest) -> TimelineCompareOut:
    """Before/after timeline: zero allocation vs provided allocation."""
    scenario = _builder_to_scenario(req)
    alloc = CandidateAllocation(**req.allocation.model_dump()) if req.allocation else CandidateAllocation(0.25, 0.25, 0.25, 0.25)
    before = _run_timeline(scenario, CandidateAllocation(0, 0, 0, 0))
    after = _run_timeline(scenario, alloc)
    return TimelineCompareOut(before=before, after=after)


# ── Export endpoint ───────────────────────────────────────────────────────────

@app.post("/export")
def export(req: SweepRequest, request: fastapi.Request) -> StreamingResponse:
    check_rate_limit(export_limiter, request)
    from shelterpulse.core.export import export_results

    scenario = _get_scenario()
    seeds = make_seed_set(scenario.seed, req.n_replications)
    results = run_optimization_sweep(
        scenario, budget=scenario.total_intervention_budget,
        n_candidates=req.n_candidates, seed_set=seeds, use_bo=req.use_bo,
    )
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        paths = export_results(scenario, results, seeds, out_dir)
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in paths:
                zf.write(p, p.name)
        buf.seek(0)
        return StreamingResponse(
            buf,
            media_type="application/zip",
            headers={"Content-Disposition": "attachment; filename=shelterpulse-results.zip"},
        )
